# Generated by Django 2.2.20 on 2021-05-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0005_user_paypal_subscription_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
